import{a as $,S as q,i as l}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))u(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(o){if(o.ep)return;o.ep=!0;const a=r(o);fetch(o.href,a)}})();let p=3;async function m(e,t){const r=await $.get("https://pixabay.com/api/",{params:{key:"56574812-7e56c45bcaff458824f0ca6f0",q:e,image_type:"photo",orientation:"horizontal",webformatWidth:180,safesearch:!0,per_page:p,page:t}});return console.log(r.data.total),console.log(r.data.totalHits),console.log(r.data.hits),{...r.data,perPage:p}}const y=document.querySelector(".gallery");let S=new q(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:.8});function g(e){const t=e.map(r=>`<li class="gallery-item">
                <a href="${r.largeImageURL}">
                  <img class="gallery__image"
                       src="${r.webformatURL}"
                       alt="${r.tags}"
                       data-source="${r.largeImageURL}"
                       data-id="${r.id}">
                </a>
                <div class="description">
                  <p>Likes<span>${r.likes}</span></p>
                  <p>Views<span>${r.views}</span></p>
                  <p>Comments<span>${r.comments}</span></p>
                  <p>Downloads<span>${r.downloads}</span></p>
                </div>
            </li>`).join("");y.insertAdjacentHTML("beforeend",t),S.refresh()}function v(){y.innerHTML=""}function f(){let e=document.querySelector(".loader");if(!e){e=document.createElement("div"),e.className="loader";const t=document.querySelector(".gallery");t.parentElement.insertBefore(e,t)}e.style.display="block"}function h(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function L(e){e.style.display="block"}function w(e){e.style.display="none"}const P=document.querySelector('[name="search-text"]'),R=document.querySelector(".form"),n=document.querySelector(".load-more-btn");let s=1,i="",d=null;R.addEventListener("submit",async e=>{if(e.preventDefault(),i=P.value.trim(),i!==""){s=1,v(),w(n);try{f();const t=await m(i,s);if(t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.ceil(t.totalHits/t.perPage),g(t.hits),s<=d&&L(n)}catch(t){l.error({message:t.message,position:"topRight"})}finally{h()}}});n.addEventListener("click",async()=>{s++,w(n);try{f();const e=await m(i,s);if(e.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits);const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}s<=d&&L(n)}catch(e){l.error({message:e.message,position:"topRight"})}finally{h()}});
//# sourceMappingURL=index.js.map
