import{a as w,S as $,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))p(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&p(c)}).observe(document,{childList:!0,subtree:!0});function r(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function p(o){if(o.ep)return;o.ep=!0;const a=r(o);fetch(o.href,a)}})();let y=15;async function f(e,t){const r=await w.get("https://pixabay.com/api/",{params:{key:"56574812-7e56c45bcaff458824f0ca6f0",q:e,image_type:"photo",orientation:"horizontal",webformatWidth:180,safesearch:!0,per_page:y,page:t}});return console.log(r.data.total),console.log(r.data.totalHits),console.log(r.data.hits),{...r.data,perPage:y}}const m=document.querySelector(".gallery");let q=new $(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:.8});function g(e){const t=e.map(r=>`<li class="gallery-item">
                <a href="${r.largeImageURL}">
                  <img class="gallery__image"
                       src="${r.webformatURL}"
                       alt="${r.tags}"
                       data-source="${r.largeImageURL}"
                       data-id="${r.id}">
                </a>
                <div class="description">
                  <p>Likes<span>${r.likes}</span></p>
                  <p>Views<span>${r.views}</span></p>
                  <p>Comments<span>${r.comments}</span></p>
                  <p>Downloads<span>${r.downloads}</span></p>
                </div>
            </li>`).join("");m.insertAdjacentHTML("beforeend",t),q.refresh()}function S(){m.innerHTML=""}function h(){let e=document.querySelector(".loader");if(!e){e=document.createElement("div"),e.className="loader";const t=document.querySelector(".gallery");t.parentElement.insertBefore(e,t)}e.style.display="block"}function L(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function v(e){e.style.display="block"}function d(e){e.style.display="none"}const P=document.querySelector('[name="search-text"]'),R=document.querySelector(".form"),s=document.querySelector(".load-more-btn");let i=1,l="",u=null;R.addEventListener("submit",async e=>{if(e.preventDefault(),l=P.value.trim(),l!==""){i=1,S(),d(s);try{h();const t=await f(l,i);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=Math.ceil(t.totalHits/t.perPage),g(t.hits),i<u?v(s):n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){n.error({message:t.message,position:"topRight"})}finally{L()}}});s.addEventListener("click",async()=>{i++,d(s);try{h();const e=await f(l,i);if(e.hits.length===0){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d(s);return}g(e.hits);const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}i<u?v(s):n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){n.error({message:e.message,position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
